plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\html websites\\Agency_Master\\_REPORT_FACTORY\\cloud_stacks\\the-one-movers\\github-pages"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]